#!/bin/bash
set -e -o pipefail
sudo apt update
sudo apt -V dist-upgrade
sudo apt autoremove --purge
sudo snap refresh
# clean residual config
sudo apt purge $(dpkg -l | grep '^rc' | awk '{print $2}')
mise up
# update firmware - disable on VMs
sudo fwupdmgr refresh && sudo fwupdmgr get-updates && sudo fwupdmgr update
